services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - db_user
      - db_password
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_HOST: db
      DB_NAME: mydb
      PORT: 5000
    secrets:
      - db_user
      - db_password
    volumes:
      - .:/app
    expose:
      - "5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx  # ou ./nginx/Dockerfile si tu préfères le placer dans un dossier
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data:

secrets:
  db_user:
    external: true
  db_password:
    external: true
