export const ALL_PHRASES = [
  "Bonjour, comment allez-vous ?",
  "Le ciel est bleu aujourd'hui.",
  "J'aime apprendre le développement web.",
  "Le chat dort sur le canapé.",
  "Il est important de bien dormir.",
  "La pluie tombe doucement ce matin.",
  "Les oiseaux chantent dans les arbres.",
  "Je bois du café tous les matins.",
  "La programmation peut être très amusante.",
  "Elle lit un livre passionnant.",
  "Nous partons en vacances demain.",
  "Il fait chaud en été.",
  "Les fleurs poussent au printemps.",
  "Il neige en hiver dans les montagnes.",
  "Le soleil brille fort aujourd'hui.",
  "Ils jouent au football au parc.",
  "Elle cuisine un gâteau au chocolat.",
  "L’ordinateur est éteint.",
  "J'écoute de la musique classique.",
  "Les enfants vont à l’école.",
  "Il est midi, l’heure du déjeuner.",
  "Je dois aller faire les courses.",
  "Le vent souffle fort dehors.",
  "Elle porte une robe rouge.",
  "Ils regardent un film ce soir.",
  "Le train part à huit heures.",
  "Il écrit une lettre à son ami.",
  "La mer est calme aujourd'hui.",
  "Je vais au travail à vélo.",
  "Il fait noir dans la pièce.",
  "Elle danse sur la musique.",
  "Nous mangeons des crêpes ce soir.",
  "Le téléphone sonne dans le salon.",
  "Les enfants dessinent sur la table.",
  "Je prends une douche froide.",
  "Il faut arroser les plantes.",
  "Le chien court dans le jardin.",
  "Elle met ses chaussures.",
  "Je lis le journal du matin.",
  "Le feu est rouge, attendons.",
  "Elle parle trois langues.",
  "Je me lève à sept heures.",
  "Ils vont au marché le samedi.",
  "Elle aime les romans policiers.",
  "Le café est trop chaud.",
  "Le réveil a sonné trop tôt.",
  "Je regarde par la fenêtre.",
  "La soupe est prête à être servie.",
  "Il fait un dessin au crayon.",
  "Le chat saute sur la table.",
  "Nous écoutons la radio.",
  "Elle met la table pour le dîner.",
  "Je cherche mes clés.",
  "Il pleut depuis ce matin.",
  "Je ferme la porte à clé.",
  "Ils habitent dans un grand appartement.",
  "Le film commence à vingt heures.",
  "Elle joue du piano tous les soirs.",
  "Je porte un pull en laine.",
  "Les feuilles tombent en automne.",
  "Il range ses affaires dans le sac.",
  "Je prépare un repas pour ce soir.",
  "Elle appelle sa mère tous les jours.",
  "Le métro est bondé ce matin.",
  "Il oublie toujours son parapluie.",
  "Je mets mes lunettes pour lire.",
  "Elle travaille dans une librairie.",
  "Le bébé dort profondément.",
  "Ils arrivent à la gare.",
  "Je prends un taxi pour l’aéroport.",
  "Elle nettoie la cuisine.",
  "Je vais à la bibliothèque.",
  "Il joue de la guitare.",
  "Nous chantons une chanson.",
  "Elle peint un paysage.",
  "Je fais du yoga le matin.",
  "Ils prennent leur petit-déjeuner.",
  "Il raconte une histoire drôle.",
  "Elle apprend à conduire.",
  "Je regarde les étoiles.",
  "Il range sa chambre.",
  "Le chat miaule pour manger.",
  "Nous faisons une promenade.",
  "Elle lit un poème à voix haute.",
  "Je fais une sieste après le déjeuner.",
  "Le voisin joue de la batterie.",
  "Elle tricote une écharpe.",
  "Je cuisine des pâtes.",
  "Il allume la lumière.",
  "Nous jouons aux cartes.",
  "Elle fait ses devoirs.",
  "Je bois un verre d’eau.",
  "Il prend une photo.",
  "Nous décorons le sapin de Noël.",
  "Elle regarde la télévision.",
  "Je fais les courses au supermarché.",
  "Il construit un château de sable.",
  "Nous jouons dans la neige.",
  "Elle cueille des fleurs.",
  "Je lis un article intéressant.",
  "Il marche dans la forêt.",
  "Nous allons au zoo dimanche.",
  "Elle dessine un chat sur le mur.",
  "Je prépare mon sac pour l’école."
];
