name: Build and Publish Docker Images

on:
  push:
    branches:
      - main   # ou la branche que tu veux

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: Dockerfile   # Dockerfile pour backend
        push: true
        tags: ghcr.io/baloo54/backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: Dockerfile  # Dockerfile pour frontend
        push: true
        tags: ghcr.io/baloo54/frontend:latest
